export const homeConstants = {
  LOAD_MORE_IMAGES: 'LOAD_MORE_IMAGES',
  LOADING_MORE_IMAGES: 'LOADING_MORE_IMAGES',
  MORE_IMAGES_LOADED: 'MORE_IMAGES_LOADED',
  SHOW_LOADING_IMAGES_ERROR: 'SHOW_LOADING_IMAGES_ERROR',
}